### ISSUE TITLE
Expected CODE symbol

### ISSUE THREAD

**Issue by snowhax** [KeenSecurityLab/BinAbsInspector#22]
this line has a error in function getVarArgsSignature

DataTypeSymbol symbol = HighFunctionDBUtil.readOverride(symbols[0]);

log:
[INFO  - BinAbsInspector] Running solver on "entry()" function
 ERROR REPORT SCRIPT ERROR:  ( /bin/ls )  /root/.ghidra/.ghidra_10.1.2_PUBLIC/Extensions/BinAbsInspector/ghidra_scripts/BinAbsInspector.java : Expected CODE symbol (HeadlessAnalyzer) java.lang.IllegalArgumentException: Expected CODE symbol
	at ghidra.program.model.pcode.DataTypeSymbol.readSymbol(DataTypeSymbol.java:128)
	at ghidra.program.model.pcode.HighFunctionDBUtil.readOverride(HighFunctionDBUtil.java:704)
	at com.bai.env.funcs.externalfuncs.VarArgsFunctionBase.getVarArgsSignature(VarArgsFunctionBase.java:157)
	at com.bai.checkers.MemoryCorruption.checkExternalCallParameters(MemoryCorruption.java:284)
	at com.bai.solver.PcodeVisitor.visit_CALL(PcodeVisitor.java:684)
	at com.bai.solver.PcodeVisitor.visit(PcodeVisitor.java:1334)
	at com.bai.solver.PcodeVisitor.visit(PcodeVisitor.java:1466)
	at com.bai.env.Context.loop(Context.java:304)
	at com.bai.env.Context.mainLoop(Context.java:463)
	at com.bai.solver.InterSolver.run(InterSolver.java:35)
	at BinAbsInspector.analyze(BinAbsInspector.java:95)
	at BinAbsInspector.run(BinAbsInspector.java:152)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:379)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:234)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:212)
	at ghidra.app.util.headless.HeadlessAnalyzer.runScript(HeadlessAnalyzer.java:576)
	at ghidra.app.util.headless.HeadlessAnalyzer.runScriptsList(HeadlessAnalyzer.java:909)
	at ghidra.app.util.headless.HeadlessAnalyzer.analyzeProgram(HeadlessAnalyzer.java:1057)
	at ghidra.app.util.headless.HeadlessAnalyzer.processFileWithImport(HeadlessAnalyzer.java:1550)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1688)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1753)
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:445)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:121)
	at ghidra.GhidraLauncher.launch(GhidraLauncher.java:59)
	at ghidra.Ghidra.main(Ghidra.java:47)

startup command:
analyzeHeadless ~ tmp  "-deleteProject" "-overwrite" "-postScript" "BinAbsInspector.java" "@@-all" -import /bin/ls

**Comment by MatthewShao** [comment]
Could you please provide the sample `/bin/ls` file?

**Comment by snowhax** [comment]
> Could you please provide the sample `/bin/ls` file?

lol 哥，就用你docker里的/bin/ls

**Comment by zyq8709** [comment]
原因已查明，随后会有pr进行修复
