### ISSUE TITLE
some mistakes occured when i analysize a stackoverflow file

### ISSUE THREAD

**Issue by MuRKuo** [KeenSecurityLab/BinAbsInspector#31]
![图片](https://user-images.githubusercontent.com/31273358/166265267-7fc12fa3-3c33-4313-b23b-858494a62113.png)

**Comment by MuRKuo** [comment]
Could not initialize class com.microsoft.z3.Native
java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.z3.Native
	at com.microsoft.z3.Context.<init>(Context.java:42)
	at com.bai.util.Utils.checkZ3Installation(Utils.java:307)
	at BinAbsInspector.run(BinAbsInspector.java:136)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:379)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:234)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:212)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:47)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
Build Date: 2022-Apr-21 1210 EDT
Ghidra Version: 10.1.3
Java Home: C:\tools9527\tools\java\java11
JVM Version: Oracle Corporation 11.0.7
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-T7GJSKA

**Comment by MatthewShao** [comment]
The error message indicated that you did not install z3 solver dependency correctly. Please refer to https://github.com/KeenSecurityLab/BinAbsInspector#installation. Besides, our release was only tested on Ghidra 10.1.2, not sure if it can work properly on 10.1.3.
