### ISSUE TITLE
jar: unknown protocol

### ISSUE THREAD

**Issue by now4yreal** [KeenSecurityLab/BinAbsInspector#58]
Don't know why, I meet this error:

```
INFO  REPORT: Analysis succeeded for file: /test3 (HeadlessAnalyzer)
INFO  SCRIPT: /bai/ghidra_10.1.2_PUBLIC/Ghidra/Extensions/BinAbsInspector/ghidra_scripts/BinAbsInspector.java (HeadlessAnalyzer)
Loaded config: Config{z3TimeOut=1000, isDebug=false, isOutputJson=true, K=50, callStringK=3, checkers=[CWE676, CWE78, CWE467, CWE426, CWE134, CWE190, CWE367], entryAddress='null', timeout=-1, isEnableZ3=t
rue, z3Tactics=[], externalMapPath=null}
2022-09-13 17:43:33,156 main ERROR Invalid URL jar:file:/bai/ghidra_10.1.2_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml java.net.MalformedURLException: Unknown protocol: jar
        at java.base/java.net.URL.<init>(URL.java:708)
        at java.base/java.net.URL.fromURI(URL.java:748)
        at java.base/java.net.URI.toURL(URI.java:1139)
        at org.apache.logging.log4j.core.config.ConfigurationSource.fromUri(ConfigurationSource.java:330)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:505)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:498)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:422)
        at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:323)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:695)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:716)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:270)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:245)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:176)
        at com.bai.util.Logging.init(Logging.java:46)
        at BinAbsInspector.run(BinAbsInspector.java:132)
        at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:379)
        at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:234)
        at ghidra.app.script.GhidraScript.execute(GhidraScript.java:212)
        at ghidra.app.util.headless.HeadlessAnalyzer.runScript(HeadlessAnalyzer.java:576)
        at ghidra.app.util.headless.HeadlessAnalyzer.runScriptsList(HeadlessAnalyzer.java:909)
        at ghidra.app.util.headless.HeadlessAnalyzer.analyzeProgram(HeadlessAnalyzer.java:1057)
        at ghidra.app.util.headless.HeadlessAnalyzer.processFileNoImport(HeadlessAnalyzer.java:1146)
        at ghidra.app.util.headless.HeadlessAnalyzer.processFolderNoImport(HeadlessAnalyzer.java:1313)
        at ghidra.app.util.headless.HeadlessAnalyzer.processNoImport(HeadlessAnalyzer.java:1342)
        at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:442)
        at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:121)
        at ghidra.GhidraLauncher.launch(GhidraLauncher.java:59)
        at ghidra.Ghidra.main(Ghidra.java:47)                                                                                                                                                               Caused by: java.lang.IllegalStateException: Unknown protocol: jar
        at org.apache.felix.framework.URLHandlersStreamHandlerProxy.parseURL(URLHandlersStreamHandlerProxy.java:373)
        at java.base/java.net.URL.<init>(URL.java:703)
```

And I solved this following the guide:
https://test.ocom.vn/?url=github.com/NationalSecurityAgency/ghidra/issues/3355

Hope someone else meets this problem could solve this quickly(Although I spend two days on it :( )

**Comment by now4yreal** [comment]
And, my java version is jdk-17.0.1

**Comment by Jackey0** [comment]
师傅，还记得这个怎么解决的吗，https://test.ocom.vn/?url=github.com/NationalSecurityAgency/ghidra/issues/3355这里面的处理方式是在launch.properties文件中添加VMARGS配置，但是我添加了之后还是存在这个问题。我jdk版本是jdk 17.0.1，ghidra版本是10.1
